### PR TITLE
BUILD-400: feature file for rhel entitlement using shared secret

### PR DESCRIPTION
**Pull request by prietyc123**
- Test scenario for rhel entitlement subscription using shared secret

### CODE REVIEW

**Comment by prietyc123** [comment]
/assign @jitendar-singh 
for qe-approve label

**Comment by gabemontero** [comment]
/label docs-approved

@rolfedh already has doc's cooking for this story under through my Jira items

**Comment by gabemontero** [comment]
/label qe-approved

this PR is from QE :-)

**Pull request merged**
