### PR TITLE
Use single script for deployment

### PR DESCRIPTION
**Pull request by adambkaplan**
- Add deploy make target
- Update deploy.sh to allow driver image and registrar image to be
  overrode.
- Update install doc to use make target
- Remove test code that runs its own driver deployment.

### CODE REVIEW

**Comment by adambkaplan** [comment]
/hold

Needs https://github.com/openshift/release/pull/20960 to work correctly.

**Comment by gabemontero** [comment]
from one of the e2e's: 

`Deploying using csi driver registry.build02.ci.openshift.org/ci-op-pgpdqqrj/pipeline@sha256:cb813c886ba2b84a51fcc4d1004355f31aefe62b733b087a973a1f3d0b710505`

good to go

**Pull request merged**
