### PR TITLE
Fixed 'deploy' make target with custom driver image

### PR DESCRIPTION
**Pull request by alicerum**
If hostname of the image contains port, and semicolon, deploy script will try to split on it, and create an incorrect kustomize yaml.

Should only split on the semicolon after the last slash, and if tag does not exist, substitute it with `latest`.

### CODE REVIEW

**Review by otaviof — APPROVED** [review]
Nice bash skills, @alicerum! 👏🏼 

/lgtm -- but I'm not on the "owners" file yet

**Comment by gabemontero** [comment]
can you run `shellcheck` against your updated deploy.sh @alicerum and make any corrections it asks for?

once you have a clean `shellcheck` version I'll approve

**Comment by gabemontero** [comment]
> can you run `shellcheck` against your updated deploy.sh @alicerum and make any corrections it asks for?
> 
> once you have a clean `shellcheck` version I'll approve

and admittedly, shellcheck may catch things  that already existed previously :-)

**Comment by alicerum** [comment]
@gabemontero done. thank you, I never knew `shellcheck` existed, it's an amazing tool.

**Comment by alicerum** [comment]
@gabemontero could you please approve if you are okay with the changes? i'd create another PR on top of this change

**Pull request merged**
