### PR TITLE
OCPBUGS-23108: Should reference configmaps instead of secrets

### LINKED ISSUE #150: update/recreate target configmap, the data of csi volume not update/recreate

### PR DESCRIPTION
**Pull request by little-guy-lxr**

### CODE REVIEW

**Comment by coreydaley** [comment]
/assign @gabemontero 
Could you please give this a quick once over and make sure it looks right?

**Review by gabemontero — APPROVED** [review]
/approve
/lgtm

yep a classic copy/paste error or picked the wrong option on auto-complete error @coreydaley 

did you just notice this, or did this come up during some debug / triage somehow?

**Pull request merged**
