### PR TITLE
BUILD-1013: Update Konflux References and CEL Expr

### PR DESCRIPTION
**Pull request by avinal**
## Changes

- updated konflux references to point to correct component
- updated cel expression to trigger pipelines on specific changes only
- updated pipelines with latest images
- fix label and cve violations
- Fixes [BUILD-1013](https://issues.redhat.com//browse/BUILD-1013) [BUILD-1015](https://issues.redhat.com//browse/BUILD-1015)

Signed-off-by: Avinal Kumar <avinal@redhat.com>

### CODE REVIEW

**Review by sayan-biswas — APPROVED** [review]

**Comment by sayan-biswas** [comment]
@avinal Requires valid JIRA ref for merging

**Comment by adambkaplan** [comment]
/retitle BUILD-1012: Update Konflux References and CEL Expr

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Comment by ramessesii2** [comment]
@avinal the EC Pipelines shows the following violation:
```
- metadata:
[report]       code: labels.disallowed_inherited_labels
[report]       collections:
[report]       - redhat
[report]       description: Check that certain labels on the image have different values than
[report]         the labels from the parent image. If the label is inherited from the parent
[report]         image but not redefined for the image, it will contain an incorrect value
[report]         for the image. Use the rule data `disallowed_inherited_labels` key to set
[report]         the list of labels to check, or the `fbc_disallowed_inherited_labels` key
[report]         for fbc images. To exclude this rule add "labels.disallowed_inherited_labels:io.k8s.description"
[report]         to the `exclude` section of the policy configuration.
[report]       solution: Update the image build process to overwrite the inherited labels.
[report]       term: io.k8s.description
[report]       title: Disallowed inherited labels
[report]     msg: The "io.k8s.description" label should not be inherited from the parent image
```
Was it supposed to be fixed along this PR?

**Comment by sayan-biswas** [comment]
Closing this, we have added CEL filters in the release streams, that will be cherry-picked in this branch.

**Pull request closed without merging**
